# Source: minio-operator/templates/console-ui.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: console-sa
  namespace: minio-operator
---
# Source: minio-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio-operator
  namespace: minio-operator
  labels:

    helm.sh/chart: minio-operator-4.1.1
    app.kubernetes.io/name: minio-operator
    app.kubernetes.io/instance: minio-operator-1623358372
    app.kubernetes.io/version: "v4.1.1"
    app.kubernetes.io/managed-by: Helm
---
# Source: minio-operator/templates/console-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: console-secret
  namespace: minio-operator
type: Opaque
data:
  ## Passphrase to encrypt jwt payload
  CONSOLE_PBKDF_PASSPHRASE: U0VDUkVU
  ## Salt to encrypt jwt payload
  CONSOLE_PBKDF_SALT: U0VDUkVU
  ## MinIO User Access Key (used for Console Login)
  CONSOLE_ACCESS_KEY: WU9VUkNPTlNPTEVBQ0NFU1M=
  ## MinIO User Secret Key (used for Console Login)
  CONSOLE_SECRET_KEY: WU9VUkNPTlNPTEVTRUNSRVQ=
---
# Source: minio-operator/templates/tenant-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: minio1-secret
  namespace: minio-operator
type: Opaque
data:
  ## Access Key for MinIO Tenant
  accesskey: bWluaW8=
  ## Secret Key for MinIO Tenant
  secretkey: bWluaW8xMjM=
---
# Source: minio-operator/templates/console-ui.yaml
apiVersion: v1
data:
  CONSOLE_PORT: "9090"
  CONSOLE_TLS_PORT: "9443"
kind: ConfigMap
metadata:
  name: console-env
  namespace: minio-operator
---
# Source: minio-operator/templates/cluster-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: minio-operator-role
rules:
  - apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - get
      - update
      - list
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - events
      - configmaps
    verbs:
      - get
      - watch
      - create
      - list
      - delete
      - deletecollection
      - update
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - watch
      - create
      - update
      - list
      - delete
      - deletecollection
  - apiGroups:
      - apps
    resources:
      - statefulsets
      - deployments
    verbs:
      - get
      - create
      - list
      - patch
      - watch
      - update
      - delete
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - create
      - list
      - patch
      - watch
      - update
      - delete
  - apiGroups:
      - "certificates.k8s.io"
    resources:
      - "certificatesigningrequests"
      - "certificatesigningrequests/approval"
      - "certificatesigningrequests/status"
    verbs:
      - update
      - create
      - get
      - delete
  - apiGroups:
      - certificates.k8s.io
    resourceNames:
      - kubernetes.io/legacy-unknown
      - kubernetes.io/kube-apiserver-client
      - kubernetes.io/kubelet-serving
    resources:
      - signers
    verbs:
      - approve
      - sign
  - apiGroups:
      - minio.min.io
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - min.io
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - get
      - create
      - list
---
# Source: minio-operator/templates/console-ui.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: console-sa-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - watch
  - create
  - list
  - patch
  - update
  - deletecollection
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  - services
  - events
  - resourcequotas
  - nodes
  verbs:
  - get
  - watch
  - create
  - list
  - patch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - deletecollection
  - list
  - get
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - watch
  - create
  - list
  - patch
- apiGroups:
  - apps
  resources:
  - statefulsets
  - deployments
  verbs:
  - get
  - create
  - list
  - patch
  - watch
  - update
  - delete
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - create
  - list
  - patch
  - watch
  - update
  - delete
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  - certificatesigningrequests/approval
  - certificatesigningrequests/status
  verbs:
  - update
  - create
  - get
- apiGroups:
  - minio.min.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - min.io
  resources:
  - '*'
  verbs:
  - '*'
---
# Source: minio-operator/templates/cluster-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: minio-operator-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: minio-operator-role
subjects:
  - kind: ServiceAccount
    name: minio-operator
    namespace: minio-operator
---
# Source: minio-operator/templates/console-ui.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: console-sa-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: console-sa-role
subjects:
- kind: ServiceAccount
  name: console-sa
  namespace: minio-operator
---
# Source: minio-operator/templates/console-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: "console"
  namespace: minio-operator
  labels:
    helm.sh/chart: minio-operator-4.1.1
    app.kubernetes.io/name: minio-operator
    app.kubernetes.io/instance: minio-operator-1623358372
    app.kubernetes.io/version: "v4.1.1"
    app.kubernetes.io/managed-by: Helm
spec:
  ports:
  - name: http
    port: 9090
  - name: https
    port: 9443
  selector:
    app.kubernetes.io/name: minio-operator
    app.kubernetes.io/instance: minio-operator-1623358372-console
---
# Source: minio-operator/templates/operator-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: "operator"
  namespace: minio-operator
  labels:
    helm.sh/chart: minio-operator-4.1.1
    app.kubernetes.io/name: minio-operator
    app.kubernetes.io/instance: minio-operator-1623358372
    app.kubernetes.io/version: "v4.1.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 4222
      name: http
    - port: 4233
      name: https
  selector:
    app.kubernetes.io/name: minio-operator
    app.kubernetes.io/instance: minio-operator-1623358372
---
# Source: minio-operator/templates/console-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-operator-1623358372-console
  namespace: minio-operator
  labels:
    helm.sh/chart: minio-operator-4.1.1
    app.kubernetes.io/name: minio-operator
    app.kubernetes.io/instance: minio-operator-1623358372
    app.kubernetes.io/version: "v4.1.1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: minio-operator
      app.kubernetes.io/instance: minio-operator-1623358372-console
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minio-operator
        app.kubernetes.io/instance: minio-operator-1623358372-console
    spec:
      serviceAccountName: console-sa
      containers:
        - name: minio-operator
          image: "minio/console:v0.7.4"
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 9090
            name: http
          - containerPort: 9443
            name: https
          args:
          - server
          env:
          - name: CONSOLE_OPERATOR_MODE
            value: "on"
          resources:
            {}
---
# Source: minio-operator/templates/operator-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "minio-operator"
  namespace: minio-operator
  labels:
    helm.sh/chart: minio-operator-4.1.1
    app.kubernetes.io/name: minio-operator
    app.kubernetes.io/instance: minio-operator-1623358372
    app.kubernetes.io/version: "v4.1.1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: minio-operator
      app.kubernetes.io/instance: minio-operator-1623358372
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minio-operator
        app.kubernetes.io/instance: minio-operator-1623358372
    spec:
      serviceAccountName: minio-operator
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: minio-operator
          image: "minio/operator:v4.1.1"
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 200m
              ephemeral-storage: 500Mi
              memory: 256Mi
---
# Source: minio-operator/templates/tenant.yaml
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minio1
  namespace: 
  ## Optionally pass labels to be applied to the statefulset pods
  labels:
    app: minio
  
  
spec:
  image: minio/minio:RELEASE.2021-06-07T21-40-51Z
  imagePullPolicy: IfNotPresent
  ## Secret with credentials to be used by MinIO Tenant.
  credsSecret:
    name: minio1-secret
  
  pools:
    - servers: 4
      volumesPerServer: 4
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          storageClassName: longhorn
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
  
  mountPath: /export
  subPath: /data
  requestAutoCert: true
  s3:
    bucketDNS: false
  podManagementPolicy: Parallel
  
  console:
    image: minio/console:v0.7.4
    replicas: 1
    consoleSecret:
      name: console-secret
